### ISSUE TITLE
Minecraft 1.18.2 Forge Crash on Vault Hunters 3 Crash on Start

### ISSUE THREAD

**Issue by Aiidoneus** [cpburnz/minecraft-prometheus-exporter#19]
Hello,
Thank you for all that you did to get this working on 1.18.2! All of my 1.18.2 server on our network work besides Vault Hunters 3 modpack for whatever reason. 

https://www.curseforge.com/minecraft/modpacks/vault-hunters-1-18-2

Here is the crash report: 

https://gist.github.com/Aiidoneus/60becb44fb1289d968919db91e49c029

Is this something that can be fixed?

**Comment by cpburnz** [comment]
Thanks for the report. It looks like the tick event on two different "vault" dimensions overlapped. I didn't think it was possible for dimensions ticks to overlap. I'll make an adjustment to support overlapping dimension ticks because I suspect it's an implementation quirk of `iskallia.vault.world.data.VirtualWorlds` which initiated the tick.

**Comment by cpburnz** [comment]
I have a fix implemented [here](https://github.com/cpburnz/minecraft-prometheus-exporter/releases/tag/1.18.2-forge-1.1.0-2) if the problem is what I think it is. Can you try it out?

**Comment by cpburnz** [comment]
In that case the problem is the dimension ticks are not properly being ended (no end tick event), which would give the appearance of overlapping ticks.

**Comment by cpburnz** [comment]
Try this version [here](https://github.com/cpburnz/minecraft-prometheus-exporter/releases/tag/1.18.2-forge-1.1.0-3). Instead of throwing an IllegalStateException, it will log a DEBUG level message.

Depending on how badly behaved the ticks are on "vault" dimensions, the  "logs/debug.log" file could grow quickly. There should be a way to ignore them by configuring log4j2 but I haven't figured that out yet. If that turns out to be too cumbersome, I'll add an option to the config file to disable the messages.

**Comment by cpburnz** [comment]
Great! I skimmed the Vault Hunters mod code, and it does implement its own dimensions (virtual worlds) and multi-threads them (based on some setting). It didn't look like start/end tick events should be skipped but based on the crashes some must.

**Comment by cpburnz** [comment]
I've released v1.2.0 ([Github](https://github.com/cpburnz/minecraft-prometheus-exporter/releases/tag/1.18.2-forge-1.2.0), [Curse Forge](https://www.curseforge.com/minecraft/mc-mods/prometheus-exporter/files/5277979)). You can disable the debug message by setting `collector.mc_dimension_tick_errors` to `"IGNORE"` in `world/serverconfig/prometheus_exporter-server.toml`.
